export const SPANISH_VERBS = [
  'logré',
  'conseguí',
  'alcancé',
  'completé',
  'finalicé',
  'terminé',
  'resolví',
  'solucioné',
  'desarrollé',
  'creé',
  'construí',
  'diseñé',
  'implementé',
  'programé',
  'codifiqué',
  'escribí',
  'produje',
  'generé',
  'lideré',
  'dirigí',
  'coordiné',
  'organicé',
  'gestioné',
  'administré',
  'supervisé',
  'controlé',
  'monitoreé',
  'analicé',
  'evalué',
  'optimicé',
  'mejoré',
  'incrementé',
  'aumenté',
  'elevé',
  'potencié',
  'maximicé',
  'minimicé',
  'reduje',
  'disminuí',
  'eliminé',
  'removí',
  'quité',
  'simplifiqué',
  'automatizé',
  'digitalicé',
  'modernicé',
  'transformé',
  'migré',
  'reestructuré',
  'reorganizé',
  'innové',
  'introduje',
  'presenté',
  'propuse',
  'negocié',
  'comuniqué',
  'colaboré',
  'entrené',
  'mentoricé',
  'guié',
  'enseñé',
  'formé',
  'especialicé',
  'avancé',
  'progresé',
  'crecí',
  'escalé',
];


export const ENGLISH_VERBS = [
  'architected',
  'spearheaded',
  'developed',
  'designed',
  'optimized',
  'reduced',
  'increased',
  'managed',
  'built',
  'migrated',
  'engineered',
  'led',
  'implemented',
  'scaled',
  'delivered',
  'achieved',
  'accomplished',
  'executed',
  'performed',
  'drove',
  'directed',
  'coordinated',
  'organized',
  'administered',
  'supervised',
  'mentored',
  'guided',
  'trained',
  'collaborated',
  'communicated',
  'negotiated',
  'presented',
  'proposed',
  'analyzed',
  'evaluated',
  'assessed',
  'reviewed',
  'improved',
  'enhanced',
  'transformed',
  'modernized',
  'automated',
  'simplified',
  'streamlined',
  'restructured',
  'reorganized',
  'innovated',
  'introduced',
  'launched',
  'initiated',
  'established',
  'founded',
  'created',
  'produced',
  'generated',
  'expanded',
  'extended',
  'consolidated',
  'integrated',
  'incorporated',
  'synchronized',
  'harmonized',
  'accelerated',
  'expedited',
  'advanced',
  'progressed',
  'elevated',
  'upgraded',
  'refined',
  'polished',
  'perfected',
  'maximized',
  'minimized',
  'mitigated',
  'resolved',
  'solved',
  'troubleshot',
  'debugged',
  'rectified',
  'corrected',
  'facilitated',
  'fostered',
  'cultivated',
  'nurtured',
  'promoted',
  'advocated',
  'represented',
  'endorsed',
  'championed',
  'pioneered',
  'originated',
  'conceptualized',
  'visualized',
  'articulated',
  'demonstrated',
  'validated',
  'verified',
  'confirmed',
  'certified',
  'licensed',
  'accredited',
  'cooperated',
  'partnered',
  'aligned',
  'synergized',
  'delegate',
  'delegated',
  'empowered',
  'enabled',
  'equipped',
  'armed',
];



export const WEAK_PHRASES = {
  en: [
    'responsible for',
    'worked on',
    'helped with',
    'helped to',
    'assisted with',
    'assisted in',
    'participated in',
    'was involved in',
    'was tasked with',
    'involved in',
    'duties included',
    'contributed to',
    'hard-working',
    'hardworking',
    'team player',
    'go-getter',
    'detail oriented',
    'results-driven',
    'think outside the box',
    'think outside of the box',
    'wear many hats',
    'familiar with',
  ],
  es: [
    'responsable de',
    'responsabilidades',
    'trabajé en',
    'trabajando en',
    'ayudé con',
    'ayudé a',
    'asistí en',
    'asistí a',
    'participé en',
    'participé en el',
    'estuve involucrado',
    'colaboré en',
    'aporté a',
    'trabajador',
    'buen trabajo en equipo',
    'orientado a resultados',
    'orientada a resultados',
    'manejo de',
    'conocimientos de',
    'uso de',
  ],
};


export const PHRASE_REWRITES = {
  en: {
    'responsible for': 'Owned',
    'worked on': 'Shipped',
    'helped with': 'Delivered',
    'helped to': 'Delivered',
    'assisted with': 'Delivered',
    'assisted in': 'Delivered',
    'participated in': 'Contributed to',
    'was involved in': 'Ran',
    'was tasked with': 'Owned',
    involved: 'Ran',
    'duties included': 'Delivered',
    'contributed to': 'Delivered',
  },
  es: {
    'responsable de': 'Lideré',
    responsabilidades: 'Logros',
    'trabajé en': 'Construí',
    'trabajando en': 'Construyendo',
    'ayudé con': 'Entregué',
    'ayudé a': 'Entregué',
    'asistí en': 'Participé en',
    'asistí a': 'Participé en',
    'participé en': 'Contribuí a',
    'estuve involucrado': 'Dirigí',
    'colaboré en': 'Lideré',
    'aporté a': 'Impulsé',
  },
};

export const ATS_KEYWORDS = [
  'leadership',
  'strategic',
  'analytical',
  'communication',
  'problem-solving',
  'teamwork',
  'collaboration',
  'project management',
  'deadline',
  'budget',
  'stakeholder',
  'kpi',
  'roi',
  'revenue',
  'growth',
  'efficiency',
  'productivity',
  'performance',
  'quality',
  'innovation',
  'customer',
  'user experience',
  'agile',
  'scrum',
  'sprint',
  'cross-functional',
];

export const ATS_KEYWORDS_ES = [
  'liderazgo',
  'estratégico',
  'analítico',
  'comunicación',
  'resolución de problemas',
  'trabajo en equipo',
  'colaboración',
  'gestión de proyectos',
  'plazos',
  'presupuesto',
  'interesados',
  'kpi',
  'roi',
  'ingresos',
  'crecimiento',
  'eficiencia',
  'productividad',
  'rendimiento',
  'calidad',
  'innovación',
  'cliente',
  'experiencia de usuario',
  'agil',
  'scrum',
  'sprint',
  'multidisciplinar',
];
