const CATALOG = [
  ['JavaScript', ['js', 'java script'], 'Languages'],
  ['TypeScript', ['ts', 'type script'], 'Languages'],
  ['Python', ['py'], 'Languages'],
  ['Java', [], 'Languages'],
  ['C#', ['csharp', 'c sharp'], 'Languages'],
  ['C++', ['cpp', 'c plus'], 'Languages'],
  ['C', [], 'Languages'],
  ['Go', ['golang'], 'Languages'],
  ['Rust', [], 'Languages'],
  ['Ruby', [], 'Languages'],
  ['PHP', [], 'Languages'],
  ['Swift', [], 'Languages'],
  ['Kotlin', [], 'Languages'],
  ['Dart', [], 'Languages'],
  ['Scala', [], 'Languages'],
  ['Elixir', [], 'Languages'],
  ['Haskell', [], 'Languages'],
  ['Clojure', [], 'Languages'],
  ['Lua', [], 'Languages'],
  ['R', [], 'Languages'],
  ['MATLAB', [], 'Languages'],
  ['Groovy', [], 'Languages'],
  ['Solidity', [], 'Languages'],
  ['Zig', [], 'Languages'],
  ['Bash', ['shell', 'sh'], 'Languages'],
  ['Shell Scripting', ['shell scripting'], 'Languages'],
  ['SQL', [], 'Languages'],
  ['PL/SQL', ['plsql'], 'Languages'],
  ['T-SQL', ['tsql'], 'Languages'],
  ['HTML', [], 'Languages'],
  ['HTML5', ['html 5'], 'Languages'],
  ['CSS', [], 'Languages'],
  ['CSS3', ['css 3'], 'Languages'],
  ['Sass', ['scss'], 'Languages'],
  ['Tailwind CSS', ['tailwind'], 'Languages'],
  ['WebAssembly', ['wasm'], 'Languages'],
  ['Assembly', ['asm'], 'Languages'],
  ['VBA', [], 'Languages'],

  ['React', ['reactjs', 'react.js'], 'Frontend'],
  ['React Native', ['react-native'], 'Mobile'],
  ['React Query', ['react-query'], 'Frontend'],
  ['React Router', ['react-router'], 'Frontend'],
  ['Redux', ['redux toolkit'], 'Frontend'],
  ['Next.js', ['next', 'nextjs'], 'Frontend'],
  ['Gatsby', [], 'Frontend'],
  ['Remix', [], 'Frontend'],
  ['Astro', [], 'Frontend'],
  ['Vue', ['vuejs', 'vue.js'], 'Frontend'],
  ['Nuxt', ['nuxtjs'], 'Frontend'],
  ['Angular', ['angularjs'], 'Frontend'],
  ['Svelte', ['sveltekit'], 'Frontend'],
  ['SolidJS', ['solid js'], 'Frontend'],
  ['HTMX', ['htmx'], 'Frontend'],
  ['Alpine.js', ['alpine'], 'Frontend'],
  ['Webpack', [], 'Frontend'],
  ['Vite', [], 'Frontend'],
  ['Rollup', [], 'Frontend'],
  ['Parcel', [], 'Frontend'],
  ['esbuild', [], 'Frontend'],
  ['Storybook', ['story book'], 'Frontend'],
  ['Material UI', ['mui'], 'Frontend'],
  ['Ant Design', ['antd'], 'Frontend'],
  ['Chakra UI', ['chakra'], 'Frontend'],
  ['Shadcn UI', ['shadcn'], 'Frontend'],
  ['Three.js', ['threejs', 'three'], 'Frontend'],
  ['D3.js', ['d3'], 'Frontend'],
  ['Canvas', ['html canvas'], 'Frontend'],
  ['WebGL', [], 'Frontend'],
  ['Responsive Design', ['responsive'], 'Frontend'],
  ['Server Side Rendering', ['ssr'], 'Frontend'],
  ['Static Site Generation', ['ssg'], 'Frontend'],
  ['Micro Frontends', ['micro-frontends'], 'Frontend'],
  ['PWA', ['progressive web app'], 'Frontend'],

  ['Flutter', [], 'Mobile'],
  ['Ionic', [], 'Mobile'],
  ['SwiftUI', [], 'Mobile'],
  ['Jetpack Compose', ['compose'], 'Mobile'],
  ['Android', ['android studio'], 'Mobile'],
  ['iOS', ['ios'], 'Mobile'],
  ['React Native CLI', ['rn cli'], 'Mobile'],
  ['Expo', [], 'Mobile'],
  ['Capacitor', [], 'Mobile'],
  ['Push Notifications', ['fcm', 'apns'], 'Mobile'],

  ['Node.js', ['node', 'nodejs'], 'Backend'],
  ['Deno', [], 'Backend'],
  ['Bun', [], 'Backend'],
  ['Express', ['expressjs'], 'Backend'],
  ['NestJS', ['nest', 'nestjs'], 'Backend'],
  ['Fastify', [], 'Backend'],
  ['Koa', [], 'Backend'],
  ['Spring Boot', ['spring'], 'Backend'],
  ['Quarkus', [], 'Backend'],
  ['Micronaut', [], 'Backend'],
  ['ASP.NET', ['aspnet', 'asp net'], 'Backend'],
  ['.NET', ['dotnet', 'net'], 'Backend'],
  ['Django', [], 'Backend'],
  ['Flask', [], 'Backend'],
  ['FastAPI', ['fast api'], 'Backend'],
  ['Rails', ['ruby on rails'], 'Backend'],
  ['Laravel', [], 'Backend'],
  ['Symfony', [], 'Backend'],
  ['CodeIgniter', [], 'Backend'],
  ['Gin', ['gin gonic'], 'Backend'],
  ['Phoenix', ['phoenix framework'], 'Backend'],
  ['Actix', ['actix web'], 'Backend'],
  ['Ruby on Rails', ['ror'], 'Backend'],
  ['Phoenix Framework', ['phoenix fw'], 'Backend'],
  ['REST API', ['rest', 'restful'], 'Backend'],
  ['GraphQL', ['graph ql'], 'Backend'],
  ['gRPC', ['grpc api'], 'Backend'],
  ['WebSockets', ['websocket'], 'Backend'],
  ['Server-Sent Events', ['sse'], 'Backend'],
  ['OAuth 2.0', ['oauth2', 'oauth'], 'Backend'],
  ['OpenID Connect', ['oidc'], 'Backend'],
  ['JWT', ['json web token'], 'Backend'],
  ['Session Management', ['sessions'], 'Backend'],
  ['Rate Limiting', ['throttling'], 'Backend'],
  ['Caching', ['cache', 'redis cache'], 'Backend'],
  ['Web Security', ['appsec'], 'Backend'],
  ['OWASP Top 10', ['owasp'], 'Backend'],
  ['Input Validation', ['sanitization'], 'Backend'],
  ['Middleware', ['interceptores'], 'Backend'],
  ['WebSockets API', ['ws api'], 'Backend'],

  ['PostgreSQL', ['postgres', 'postg'], 'Data'],
  ['MySQL', ['mariadb'], 'Data'],
  ['SQLite', [], 'Data'],
  ['SQL Server', ['mssql', 'sqlserver'], 'Data'],
  ['Oracle DB', ['oracle'], 'Data'],
  ['MongoDB', ['mongo'], 'Data'],
  ['Neo4j', [], 'Data'],
  ['Redis', [], 'Data'],
  ['Memcached', ['memcache'], 'Data'],
  ['Elasticsearch', ['elastic', 'elastic search'], 'Data'],
  ['OpenSearch', [], 'Data'],
  ['Cassandra', [], 'Data'],
  ['DynamoDB', ['dynamo'], 'Data'],
  ['Couchbase', ['couch db'], 'Data'],
  ['CockroachDB', ['cockroach'], 'Data'],
  ['ClickHouse', ['click house'], 'Data'],
  ['InfluxDB', ['influx'], 'Data'],
  ['TimescaleDB', ['timescale'], 'Data'],
  ['Supabase', [], 'Data'],
  ['Firebase', ['firestore'], 'Data'],
  ['FaunaDB', ['fauna'], 'Data'],
  ['Prisma', [], 'Data'],
  ['Sequelize', [], 'Data'],
  ['TypeORM', ['type orm'], 'Data'],
  ['Drizzle ORM', ['drizzle'], 'Data'],
  ['Hibernate', [], 'Data'],
  ['SQLAlchemy', ['sql alchemy'], 'Data'],
  ['Snowflake', [], 'Data'],
  ['BigQuery', ['big query'], 'Data'],
  ['Redshift', [], 'Data'],
  ['Databricks', [], 'Data'],
  ['Apache Kafka', ['kafka'], 'Data'],
  ['RabbitMQ', ['rabbit'], 'Data'],
  ['NATS', ['nats io'], 'Data'],
  ['Pulsar', ['apache pulsar'], 'Data'],
  ['Celery', [], 'Data'],
  ['Sidekiq', [], 'Data'],
  ['GraphQL Federation', ['federation'], 'Data'],
  ['Database Sharding', ['sharding'], 'Data'],
  ['Database Replication', ['replication'], 'Data'],
  ['Data Modelling', ['data modeling'], 'Data'],
  ['Schema Design', ['data design'], 'Data'],
  ['Migrations', ['db migrations'], 'Data'],
  ['Query Optimisation', ['query optimization'], 'Data'],

  ['AWS', ['amazon web services'], 'Cloud'],

  ['S3', ['amazon s3'], 'Cloud'],
  ['EC2', ['amazon ec2'], 'Cloud'],
  ['ECS', [], 'Cloud'],
  ['EKS', [], 'Cloud'],
  ['Lambda', ['aws lambda'], 'Cloud'],
  ['RDS', [], 'Cloud'],
  ['CloudFront', ['cloud front'], 'Cloud'],
  ['Route 53', ['route53'], 'Cloud'],
  ['Azure', ['microsoft azure'], 'Cloud'],
  ['Azure DevOps', ['ado'], 'Cloud'],
  ['GCP', ['google cloud'], 'Cloud'],
  ['Bigtable', [], 'Cloud'],
  ['Cloud Run', ['cloudrun'], 'Cloud'],
  ['Vercel', [], 'Cloud'],
  ['Netlify', [], 'Cloud'],
  ['Cloudflare', [], 'Cloud'],
  ['Heroku', [], 'Cloud'],
  ['DigitalOcean', ['digital ocean'], 'Cloud'],
  ['Fly.io', ['flyio'], 'Cloud'],
  ['Render', [], 'Cloud'],
  ['Hetzner', [], 'Cloud'],
  ['OpenStack', [], 'Cloud'],
  ['Nginx', [], 'Cloud'],
  ['Apache', ['httpd'], 'Cloud'],
  ['Caddy', ['caddyserver'], 'Cloud'],
  ['Traefik', [], 'Cloud'],
  ['CDN', ['content delivery network'], 'Cloud'],
  ['Load Balancer', ['load balancing'], 'Cloud'],
  ['Linux', ['unix'], 'Cloud'],
  ['Bash Scripting', ['shell scripting 2'], 'Cloud'],

  ['Docker', [], 'Tooling'],
  ['Docker Compose', ['docker-compose'], 'Tooling'],
  ['Podman', [], 'Tooling'],
  ['Kubernetes', ['kube', 'k8s'], 'Tooling'],
  ['Helm', [], 'Tooling'],
  ['Kustomize', [], 'Tooling'],
  ['Terraform', ['iac', 'infrastructure as code'], 'Tooling'],
  ['OpenTofu', ['tofu'], 'Tooling'],
  ['Pulumi', [], 'Tooling'],
  ['Ansible', [], 'Tooling'],
  ['Argo CD', ['argocd'], 'Tooling'],
  ['Argo Workflows', ['argo'], 'Tooling'],
  ['Flux CD', ['flux'], 'Tooling'],
  ['Jenkins', [], 'Tooling'],
  ['GitHub Actions', ['actions', 'ci cd'], 'Tooling'],
  ['GitLab CI', ['gitlab ci'], 'Tooling'],
  ['CircleCI', ['circle ci'], 'Tooling'],
  ['Jest', [], 'Tooling'],
  ['Vitest', [], 'Tooling'],
  ['Maven', [], 'Tooling'],
  ['Gradle', [], 'Tooling'],
  ['npm', ['node package manager'], 'Tooling'],
  ['pnpm', [], 'Tooling'],
  ['Yarn', [], 'Tooling'],
  ['Makefile', ['make'], 'Tooling'],
  ['CMake', [], 'Tooling'],
  ['Git', ['github', 'gitlab', 'bitbucket'], 'Tooling'],
  ['Git Flow', ['gitflow'], 'Tooling'],
  ['SonarQube', ['sonar'], 'Tooling'],
  ['OpenTelemetry', ['otel'], 'Tooling'],
  ['Grafana', [], 'Tooling'],
  ['Prometheus', ['prom'], 'Tooling'],
  ['Datadog', ['data dog'], 'Tooling'],
  ['New Relic', ['newrelic'], 'Tooling'],
  ['Sentry', [], 'Tooling'],
  ['Jaeger', [], 'Tooling'],
  ['Loki', ['grafana loki'], 'Tooling'],
  ['OpenSearch Dashboards', ['kibana'], 'Tooling'],
  ['Vault', ['hashicorp vault'], 'Tooling'],
  ['Consul', ['hashicorp consul'], 'Tooling'],
  ['Artifactory', ['jfrog'], 'Tooling'],
  ['Nexus', ['sonatype nexus'], 'Tooling'],
  ['Vagrant', [], 'Tooling'],
  ['Nix', ['nixos'], 'Tooling'],
  ['Semantic Versioning', ['semver'], 'Tooling'],
  ['Monorepo', ['mono repo', 'nx'], 'Tooling'],
  ['Nx', ['nrwl'], 'Tooling'],
  ['Turborepo', ['turbo'], 'Tooling'],
  ['Lerna', [], 'Tooling'],
  ['Commitlint', ['commit lint'], 'Tooling'],
  ['Husky', [], 'Tooling'],
  ['Prettier', [], 'Tooling'],
  ['ESLint', ['eslint'], 'Tooling'],
  ['Webpack Bundle Analyzer', ['bundle analyzer'], 'Tooling'],
  ['Dependabot', ['dependabot'], 'Tooling'],
  ['Renovate', [], 'Tooling'],
  ['Sentry CLI', ['sentry cli'], 'Tooling'],
  ['Webhooks', ['web hook'], 'Tooling'],
  ['OAuth Apps', ['oauth apps'], 'Tooling'],

  ['Cypress', [], 'Testing'],
  ['Playwright', [], 'Testing'],
  ['Selenium', [], 'Testing'],
  ['Puppeteer', [], 'Testing'],
  ['Pytest', [], 'Testing'],
  ['JUnit', ['j unit'], 'Testing'],
  ['Jest Mocking', ['jest-mock'], 'Testing'],
  ['Testing Library', ['rtl'], 'Testing'],
  ['React Testing Library', ['rtl react'], 'Testing'],
  ['Supertest', ['super test'], 'Testing'],
  ['k6', ['k six'], 'Testing'],
  ['JMeter', [], 'Testing'],
  ['Gatling', [], 'Testing'],
  ['Postman', [], 'Testing'],
  ['Insomnia', [], 'Testing'],
  ['Pact', ['contract testing'], 'Testing'],
  ['Mutation Testing', ['pitest', 'stryker'], 'Testing'],
  ['Test Driven Development', ['tdd'], 'Testing'],
  ['Behaviour Driven Development', ['bdd'], 'Testing'],
  ['Acceptance Tests', ['e2e'], 'Testing'],
  ['Smoke Testing', ['smoke'], 'Testing'],
  ['Load Testing', ['load tests'], 'Testing'],
  ['Regression Testing', ['regression'], 'Testing'],
  ['Unit Testing', ['unit tests'], 'Testing'],

  ['Agile', ['agile methodologies'], 'Practices'],
  ['Scrum', [], 'Practices'],
  ['Kanban', [], 'Practices'],
  ['XP', ['extreme programming'], 'Practices'],
  ['TDD', ['test driven development'], 'Practices'],
  ['BDD', ['behaviour driven development'], 'Practices'],
  ['DDD', ['domain driven design'], 'Practices'],
  ['SDD', ['spec driven development'], 'Practices'],
  ['ETL', ['extract transform load'], 'Practices'],
  ['ELT', ['extract load transform'], 'Practices'],
  ['CI/CD', ['cicd', 'continuous integration'], 'Practices'],
  ['SPA', ['single page application'], 'Practices'],
  ['SSR', ['server side rendering'], 'Practices'],
  ['SSG', ['static site generation'], 'Practices'],
  ['ORM', ['object relational mapping'], 'Practices'],
  ['SRE', ['site reliability'], 'Practices'],
  ['PM', ['product manager'], 'Practices'],
  ['Pair Programming', ['pairing'], 'Practices'],
  ['Sprint Planning', ['sprints'], 'Practices'],
  ['Retrospective', ['retro'], 'Practices'],
  ['Waterfall', [], 'Practices'],
  ['Domain Driven Design', ['ddd'], 'Practices'],
  ['Spec Driven Development', ['sdd'], 'Practices'],
  ['Test Driven Design', ['tdd design'], 'Practices'],
  ['SOLID Principles', ['solid'], 'Practices'],
  ['Clean Architecture', ['clean arch'], 'Practices'],
  ['Hexagonal Architecture', ['ports and adapters'], 'Practices'],
  ['Microservices', ['micro services'], 'Practices'],
  ['Event Sourcing', ['event driven architecture'], 'Practices'],
  ['CQRS', ['command query responsibility'], 'Practices'],
  ['Saga Pattern', ['sagas'], 'Practices'],
  ['Serverless', ['lambda functions'], 'Practices'],
  ['Observability', ['observable'], 'Practices'],
  ['Feature Flags', ['feature toggles', 'feature management'], 'Practices'],
  ['Progressive Delivery', ['canary releases'], 'Practices'],
  ['Infrastructure as Code', ['iac 2'], 'Practices'],
  ['GitOps', ['git ops'], 'Practices'],
  ['DevOps', ['dev ops'], 'Practices'],
  ['Platform Engineering', ['platform eng'], 'Practices'],
  ['Site Reliability Engineering', ['sre'], 'Practices'],
  ['MVC', ['model view controller'], 'Practices'],
  ['MVVM', ['model view viewmodel'], 'Practices'],
  ['Design Patterns', ['patterns'], 'Practices'],
  ['SOLID', ['solid 2'], 'Practices'],
  ['Code Review', ['code reviews', 'revisiones de codigo'], 'Practices'],
  ['Documentation', ['documentacion', 'docs'], 'Practices'],
  ['Technical Writing', ['technical docs'], 'Practices'],
  ['System Design', ['diseno de sistemas'], 'Practices'],
  ['Data Structures', ['algoritmos', 'algorithms'], 'Practices'],
  ['Algorithms', ['algoritmia'], 'Practices'],
  ['Complexity Analysis', ['big o'], 'Practices'],
  ['Concurrency', ['concurrencia'], 'Practices'],
  ['Multithreading', ['multi threading'], 'Practices'],
  ['Async Programming', ['asyncio', 'asincronia'], 'Practices'],

  ['Machine Learning', ['ml'], 'Data & AI'],
  ['Deep Learning', [], 'Data & AI'],
  ['Supervised Learning', ['supervised'], 'Data & AI'],
  ['Unsupervised Learning', ['unsupervised'], 'Data & AI'],
  ['Reinforcement Learning', ['rl'], 'Data & AI'],
  ['NLP', ['natural language processing'], 'Data & AI'],
  ['Computer Vision', ['cv', 'vision'], 'Data & AI'],
  ['TensorFlow', ['tensor flow'], 'Data & AI'],
  ['PyTorch', ['torch'], 'Data & AI'],
  ['Keras', [], 'Data & AI'],
  ['scikit-learn', ['sklearn', 'scikit'], 'Data & AI'],
  ['Pandas', [], 'Data & AI'],
  ['NumPy', ['numpy'], 'Data & AI'],
  ['Polars', [], 'Data & AI'],
  ['Matplotlib', ['matplotlib'], 'Data & AI'],
  ['Seaborn', [], 'Data & AI'],
  ['Jupyter', ['notebook', 'jupyterlab'], 'Data & AI'],
  ['Hugging Face', ['huggingface', 'transformers'], 'Data & AI'],
  ['LangChain', ['lang chain'], 'Data & AI'],
  ['LangGraph', ['lang graph'], 'Data & AI'],
  ['RAG', ['retrieval augmented generation'], 'Data & AI'],
  ['LLM', ['llms', 'large language models'], 'Data & AI'],
  ['Prompt Engineering', ['prompts'], 'Data & AI'],
  ['Fine Tuning', ['finetuning'], 'Data & AI'],
  ['Embeddings', ['vector embeddings'], 'Data & AI'],
  ['Vector Databases', ['vector db', 'pgvector'], 'Data & AI'],
  ['Pinecone', [], 'Data & AI'],
  ['Weaviate', [], 'Data & AI'],
  ['OpenAI', ['gpt', 'chatgpt'], 'Data & AI'],
  ['Claude', ['claude code', 'anthropic'], 'Data & AI'],
  ['Claude Code', ['anthropic cli'], 'Data & AI'],
  ['GitHub Copilot', ['copilot'], 'Data & AI'],
  ['Gemini', ['google gemini'], 'Data & AI'],
  ['Llama', ['meta llama'], 'Data & AI'],
  ['Mistral', ['mistral ai'], 'Data & AI'],
  ['Ollama', [], 'Data & AI'],
  ['vLLM', [], 'Data & AI'],
  ['MLOps', ['ml ops'], 'Data & AI'],
  ['LLMOps', ['llm ops'], 'Data & AI'],
  ['NLP', ['natural language processing'], 'Data & AI'],
  ['ML', ['machine learning 2'], 'Data & AI'],
  ['MLflow', ['ml flow'], 'Data & AI'],
  ['Weights & Biases', ['wandb'], 'Data & AI'],
  ['Apache Spark', ['pyspark', 'spark'], 'Data & AI'],
  ['Apache Airflow', ['airflow'], 'Data & AI'],
  ['dbt', ['data build tool'], 'Data & AI'],
  ['ETL', ['elt'], 'Data & AI'],
  ['Data Engineering', ['data engineer'], 'Data & AI'],
  ['Data Analysis', ['analisis de datos'], 'Data & AI'],
  ['Data Visualisation', ['data visualization'], 'Data & AI'],
  ['Apache Kafka Streams', ['kafka streams'], 'Data & AI'],
  ['RabbitMQ Streams', ['rmq streams'], 'Data & AI'],
  ['Power BI', ['powerbi'], 'Data & AI'],
  ['Tableau', [], 'Data & AI'],
  ['Looker', [], 'Data & AI'],
  ['Excel', ['hojas de calculo'], 'Data & AI'],

  ['Figma', [], 'Product'],
  ['UX Research', ['user research'], 'Product'],
  ['UI Design', ['user interface'], 'Product'],
  ['Design Systems', ['design system'], 'Product'],
  ['Wireframing', ['wireframes'], 'Product'],
  ['Prototyping', ['prototypes'], 'Product'],
  ['Accessibility', ['a11y', 'accesibilidad'], 'Product'],
  ['WCAG', ['web content accessibility guidelines'], 'Product'],
  ['A11y', ['accesibilidad 11'], 'Product'],
  ['Inclusive Design', [], 'Product'],
  ['SEO', ['search engine optimisation'], 'Product'],
  ['Web Performance', ['core web vitals', 'lighthouse'], 'Product'],
  ['Analytics', ['google analytics'], 'Product'],
  ['A/B Testing', ['ab testing', 'split testing'], 'Product'],
  ['Product Management', ['pm'], 'Product'],
  ['Jira', [], 'Product'],
  ['Confluence', [], 'Product'],
  ['Linear', ['linear app'], 'Product'],
  ['Notion', [], 'Product'],
  ['Miro', [], 'Product'],
  ['Slack', [], 'Product'],
  ['Stakeholder Management', ['stakeholders'], 'Product'],
  ['Roadmapping', ['roadmap'], 'Product'],
];

const fold = (value) =>
  String(value || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');

const ENTRIES = CATALOG.map(([name, aliases, group]) => ({
  name,
  group,
  keys: [name, ...aliases].map(fold),
})).filter((entry, index, all) => all.findIndex((other) => other.name === entry.name) === index);

const UNIQUE = [...new Set(ENTRIES.map((entry) => entry.name))];

export function suggestSkills(prefix, { limit = 8, exclude = [] } = {}) {
  const typed = fold(String(prefix || '').trim());
  if (!typed) {
    return [];
  }
  const taken = new Set(exclude.map(fold));

  const scored = ENTRIES.filter((entry) => !taken.has(fold(entry.name)))
    .map((entry) => {
      const exact = entry.keys.findIndex((key) => key === typed);
      if (exact >= 0) {
        return { ...entry, rank: exact === 0 ? 0 : 1, length: entry.keys[exact].length };
      }
      const starts = entry.keys.findIndex((key) => key.startsWith(typed));
      if (starts < 0) {
        return null;
      }
      return { ...entry, rank: 2, length: entry.keys[starts].length };
    })
    .filter(Boolean);

  scored.sort((a, b) => a.rank - b.rank || a.length - b.length || a.name.localeCompare(b.name));

  return scored.slice(0, Math.max(0, limit)).map(({ name, group }) => ({ name, group }));
}

export function partialWordAt(markdown, caret) {
  const text = String(markdown || '');
  const at = Math.min(Math.max(0, Number(caret) || 0), text.length);
  let start = at;

  while (start > 0 && !/[\s,;|:*/_#()]/.test(text[start - 1])) {
    start -= 1;
  }
  return { word: text.slice(start, at), start, end: at };
}

export function insideSkillsSection(markdown, caret) {
  const text = String(markdown || '');
  const at = Math.min(Math.max(0, Number(caret) || 0), text.length);
  const headings = [...text.slice(0, at).matchAll(/^#{1,6}[ \t]+(.+)$/gm)];
  const last = headings[headings.length - 1];
  if (!last) {
    return false;
  }
  return /skill|habilidad|competenc|tecnolog|stack|herramient|tool/i.test(last[1]);
}

export function skillsInUse(markdown) {
  const text = String(markdown || '');
  return UNIQUE.filter((name) => {
    const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

    const pattern = `(^|[^\\p{L}\\p{N}])${escaped}(?![\\p{L}\\p{N}])`;
    return new RegExp(pattern, name.length <= 3 ? 'u' : 'iu').test(text);
  });
}

export { UNIQUE as KNOWN_SKILLS };
